//! HTML payment link support for browser-based payments.
//!
//! When `html` is enabled on the server config, 402 responses can be rendered
//! as interactive HTML payment pages instead of JSON. The page embeds a bundled
//! Solana payment UI that handles wallet connection, transaction signing, and
//! credential submission via a service worker.
//!
//! # Usage
//!
//! ```ignore
//! use solana_mpp::server::html;
//!
//! // In your HTTP handler:
//! if html::accepts_html(accept_header) && mpp.html_enabled() {
//!     if html::is_service_worker_request(query_string) {
//!         // Serve the service worker JS
//!         return respond_js(html::service_worker_js());
//!     }
//!     let challenge = mpp.charge("1.00")?;
//!     let page = html::challenge_to_html(&challenge, mpp.rpc_url(), mpp.network());
//!     return respond_html(page);
//! }
//! ```

use crate::protocol::core::PaymentChallenge;

/// Complete HTML template generated from mppx's design system (auto-generated by `html/build.ts`).
/// Contains placeholders: {{AMOUNT}}, {{DESCRIPTION}}, {{EXPIRES}}, {{DATA_JSON}}
const HTML_TEMPLATE: &str = include_str!("html/template.gen.html");

/// Bundled service worker JavaScript (from mppx, auto-generated by `html/build.ts`).
const SERVICE_WORKER_JS: &str = include_str!("html/service_worker.gen.js");

/// Query parameter that triggers serving the service worker JS file.
pub const SERVICE_WORKER_PARAM: &str = "__mpp_worker";

/// ID of the embedded data `<script>` element.
const DATA_ELEMENT_ID: &str = "__MPP_DATA__";

/// Check if an HTTP `Accept` header value includes `text/html`.
pub fn accepts_html(accept: &str) -> bool {
    accept
        .split(',')
        .any(|part| part.trim().starts_with("text/html"))
}

/// Check if a URL query string contains the service worker parameter.
pub fn is_service_worker_request(query: &str) -> bool {
    query.contains(SERVICE_WORKER_PARAM)
}

/// Returns the service worker JavaScript content.
///
/// Serve this with `Content-Type: application/javascript` when
/// `is_service_worker_request()` returns true.
pub fn service_worker_js() -> &'static str {
    SERVICE_WORKER_JS
}

/// Render a payment challenge as a self-contained HTML payment page.
///
/// The returned HTML includes:
/// - A `<pre>` block showing the challenge details
/// - An embedded JSON data block with the challenge for the payment UI
/// - The bundled payment UI script (inlined)
/// - A CSP meta tag restricting script sources
///
/// All user-controlled values are HTML-escaped to prevent XSS.
pub fn challenge_to_html(challenge: &PaymentChallenge, _rpc_url: &str, _network: &str) -> String {
    // Decode request for display
    let decoded: serde_json::Value = challenge
        .request
        .decode()
        .unwrap_or_else(|_| serde_json::json!({}));
    let amount_raw = decoded["amount"].as_str().unwrap_or("0");
    let currency = decoded["currency"].as_str().unwrap_or("SOL");
    let decimals_val = decoded["methodDetails"]["decimals"].as_u64().unwrap_or(
        if currency.to_lowercase() == "sol" {
            9
        } else {
            6
        },
    );
    let amount_f: f64 = amount_raw.parse::<f64>().unwrap_or(0.0) / 10f64.powi(decimals_val as i32);
    let display_amount = if amount_f == amount_f.floor() {
        format!("{:.0}", amount_f)
    } else {
        format!("{:.2}", amount_f)
    };
    let amount_display = match currency {
        "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        | "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU" => format!("${display_amount}"),
        "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB" => format!("${display_amount}"),
        c if c.to_lowercase() == "sol" => format!("{display_amount} SOL"),
        _ => format!("{display_amount} {}", &currency[..6.min(currency.len())]),
    };

    let description_html = challenge
        .description
        .as_deref()
        .map(|d| {
            format!(
                "<p class=\"mppx-summary-description\">{}</p>",
                escape_html(d)
            )
        })
        .unwrap_or_default();

    let expires_html = challenge
        .expires
        .as_deref()
        .map(|e| {
            format!(
                "<p class=\"mppx-summary-expires\">Expires at <time datetime=\"{iso}\" id=\"_exp\">{iso}</time></p><script>document.getElementById('_exp').textContent=new Date('{iso}').toLocaleString()</script>",
                iso = escape_html(e),
            )
        })
        .unwrap_or_default();

    // Standalone format: challenge.request stays as original base64url string.
    // This preserves HMAC integrity — the credential echoes back the exact same string.
    let embedded_data = serde_json::json!({
        "challenge": challenge,
        "network": _network,
        "rpcUrl": _rpc_url,
    });
    let data_json = serde_json::to_string(&embedded_data)
        .unwrap_or_default()
        .replace('<', "\\u003c");

    // Simple placeholder replacement on the mppx-generated template
    HTML_TEMPLATE
        .replace("{{AMOUNT}}", &escape_html(&amount_display))
        .replace("{{DESCRIPTION}}", &description_html)
        .replace("{{EXPIRES}}", &expires_html)
        .replace("{{DATA_JSON}}", &data_json)
}

/// HTML-escape a string to prevent XSS when interpolating into HTML content.
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::core::{
        types::{IntentName, MethodName},
        Base64UrlJson,
    };

    fn test_challenge(description: Option<&str>) -> PaymentChallenge {
        PaymentChallenge {
            id: "test-challenge-id".to_string(),
            realm: "test.example.com".to_string(),
            method: MethodName::new("solana"),
            intent: IntentName::new("charge"),
            request: Base64UrlJson::from_typed(
                &serde_json::json!({"amount": "1000000", "currency": "USDC", "recipient": "CXhrFZJLKqjzmP3sjYLcF4dTeXWKCy9e2SXXZ2Yo6MPY"}),
            ).unwrap(),
            expires: Some("2099-01-01T00:00:00Z".to_string()),
            description: description.map(|s| s.to_string()),
            digest: None,
            opaque: None,
        }
    }

    #[test]
    fn test_accepts_html() {
        assert!(accepts_html("text/html,application/xhtml+xml,*/*"));
        assert!(accepts_html("text/html"));
        assert!(!accepts_html("application/json"));
        assert!(!accepts_html("*/*")); // Don't match wildcard — be explicit
    }

    #[test]
    fn test_is_service_worker_request() {
        assert!(is_service_worker_request("__mpp_worker=1"));
        assert!(is_service_worker_request("foo=bar&__mpp_worker=1"));
        assert!(!is_service_worker_request("foo=bar"));
        assert!(!is_service_worker_request(""));
    }

    #[test]
    fn test_escape_html() {
        assert_eq!(
            escape_html("<script>alert('xss')</script>"),
            "&lt;script&gt;alert(&#x27;xss&#x27;)&lt;/script&gt;"
        );
    }

    #[test]
    fn test_service_worker_js_not_empty() {
        assert!(!service_worker_js().is_empty());
    }

    #[test]
    fn test_challenge_to_html_structure() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(&challenge, "http://localhost:8899", "localnet");

        assert!(html.contains("<!doctype html>"));
        assert!(html.contains("id=\"root\""));
        assert!(html.contains("__MPP_DATA__"));
        assert!(html.contains("test-challenge-id"));
        assert!(html.len() > 1000);
        assert!(html.contains("\"network\":\"localnet\""));
    }

    #[test]
    fn test_challenge_to_html_mainnet_not_test_mode() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(
            &challenge,
            "https://api.mainnet-beta.solana.com",
            "mainnet-beta",
        );
        assert!(html.contains("\"network\":\"mainnet-beta\""));
    }

    #[test]
    fn test_challenge_to_html_xss_in_description() {
        let challenge = test_challenge(Some("<script>alert('xss')</script>"));
        let html = challenge_to_html(&challenge, "http://localhost:8899", "localnet");
        // The <script> in description must be escaped in the <p> tag
        assert!(html.contains("&lt;script&gt;alert("));
        // Raw script tag should NOT appear in description context
        assert!(!html.contains("<p style=\"color:#4a5568;text-align:center\"><script>"));
    }

    #[test]
    fn test_challenge_to_html_basic_structure() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(&challenge, "http://localhost:8899", "localnet");
        // CSP is set as a response header by the server, not in the HTML meta tag.
        // Verify the HTML has the essential structural elements.
        assert!(html.contains("id=\"root\""));
        assert!(html.contains("<script"));
    }

    #[test]
    fn test_html_enabled_on_mpp() {
        let mpp = crate::server::Mpp::new(crate::server::Config {
            recipient: "CXhrFZJLKqjzmP3sjYLcF4dTeXWKCy9e2SXXZ2Yo6MPY".to_string(),
            secret_key: Some(
                "test-secret-key-long-enough-for-hmac-sha256-operations-1234567890".to_string(),
            ),
            network: "localnet".to_string(),
            html: true,
            ..Default::default()
        })
        .unwrap();

        assert!(mpp.html_enabled());
        assert_eq!(mpp.network(), "localnet");
        assert!(!mpp.rpc_url().is_empty());

        // Generate a challenge and render as HTML
        let challenge = mpp.charge("0.10").unwrap();
        let html = challenge_to_html(&challenge, mpp.rpc_url(), mpp.network());
        assert!(html.contains("<!doctype html>"));
        assert!(html.contains(&challenge.id));
    }
}
