//! HTML payment link support for browser-based payments.
//!
//! When `html` is enabled on the server config, 402 responses can be rendered
//! as interactive HTML payment pages instead of JSON. The page embeds a bundled
//! Solana payment UI that handles wallet connection, transaction signing, and
//! credential submission via a service worker.
//!
//! # Usage
//!
//! ```ignore
//! use solana_mpp::server::html;
//!
//! // In your HTTP handler:
//! if html::accepts_html(accept_header) && mpp.html_enabled() {
//!     if html::is_service_worker_request(query_string) {
//!         // Serve the service worker JS
//!         return respond_js(html::service_worker_js());
//!     }
//!     let challenge = mpp.charge("1.00")?;
//!     let page = html::challenge_to_html(&challenge, mpp.rpc_url(), mpp.network());
//!     return respond_html(page);
//! }
//! ```

use crate::protocol::core::PaymentChallenge;

/// Bundled payment UI JavaScript (auto-generated by `html/build.ts`).
const PAYMENT_UI_JS: &str = include_str!("html/payment_ui.gen.js");

/// Bundled service worker JavaScript (auto-generated by `html/build.ts`).
const SERVICE_WORKER_JS: &str = include_str!("html/service_worker.gen.js");

/// Query parameter that triggers serving the service worker JS file.
pub const SERVICE_WORKER_PARAM: &str = "__mpp_worker";

/// ID of the embedded data `<script>` element.
const DATA_ELEMENT_ID: &str = "__MPP_DATA__";

/// Check if an HTTP `Accept` header value includes `text/html`.
pub fn accepts_html(accept: &str) -> bool {
    accept
        .split(',')
        .any(|part| part.trim().starts_with("text/html"))
}

/// Check if a URL query string contains the service worker parameter.
pub fn is_service_worker_request(query: &str) -> bool {
    query.contains(SERVICE_WORKER_PARAM)
}

/// Returns the service worker JavaScript content.
///
/// Serve this with `Content-Type: application/javascript` when
/// `is_service_worker_request()` returns true.
pub fn service_worker_js() -> &'static str {
    SERVICE_WORKER_JS
}

/// Render a payment challenge as a self-contained HTML payment page.
///
/// The returned HTML includes:
/// - A `<pre>` block showing the challenge details
/// - An embedded JSON data block with the challenge for the payment UI
/// - The bundled payment UI script (inlined)
/// - A CSP meta tag restricting script sources
///
/// All user-controlled values are HTML-escaped to prevent XSS.
pub fn challenge_to_html(challenge: &PaymentChallenge, rpc_url: &str, network: &str) -> String {
    let challenge_json = serde_json::to_string_pretty(challenge).unwrap_or_default();

    // Build embedded data in the standalone format (challenge.request stays as base64url)
    let embedded_data = serde_json::json!({
        "challenge": challenge,
        "network": network,
        "rpcUrl": rpc_url,
    });
    let embedded_json = serde_json::to_string(&embedded_data).unwrap_or_default();

    // Decode request for display
    let decoded: serde_json::Value = challenge
        .request
        .decode()
        .unwrap_or_else(|_| serde_json::json!({}));
    let amount_raw = decoded["amount"].as_str().unwrap_or("0");
    let currency = decoded["currency"].as_str().unwrap_or("SOL");
    let decimals_val = decoded["methodDetails"]["decimals"].as_u64().unwrap_or(
        if currency.to_lowercase() == "sol" {
            9
        } else {
            6
        },
    );
    let amount_f: f64 = amount_raw.parse::<f64>().unwrap_or(0.0) / 10f64.powi(decimals_val as i32);
    let display_amount = if amount_f == amount_f.floor() {
        format!("{:.0}", amount_f)
    } else {
        format!("{:.2}", amount_f)
    };

    // Known stablecoin symbols
    let display_currency = match currency {
        "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        | "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU" => "USDC",
        "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB" => "USDT",
        c if c.to_lowercase() == "sol" => "SOL",
        _ => &currency[..6.min(currency.len())],
    };
    let amount_display = if display_currency == "SOL" {
        format!("{} SOL", display_amount)
    } else {
        format!("${}", display_amount)
    };

    let description_html = challenge
        .description
        .as_deref()
        .map(|d| {
            format!(
                "<div style=\"font-size:14px;color:#666;margin-bottom:16px\">{}</div>",
                escape_html(d)
            )
        })
        .unwrap_or_default();

    let test_badge = if matches!(network, "devnet" | "localnet") {
        format!("<span style=\"font-size:11px;color:#888;background:#f0f0f0;padding:2px 8px;border-radius:4px;margin-left:8px\">{}</span>", network)
    } else {
        String::new()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>Payment Required</title>
<style>
:root {{ color-scheme: light dark; }}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; min-height: 100vh; display: flex; align-items: center; justify-content: center; background: light-dark(#fafafa, #0a0a0a); color: light-dark(#111, #eee); }}
.card {{ max-width: 380px; width: 100%; padding: 32px; border-radius: 12px; border: 1px solid light-dark(#e5e5e5, #2e2e2e); background: light-dark(#fff, #141414); }}
.badge {{ font-size: 11px; font-weight: 500; color: light-dark(#666, #999); background: light-dark(#f5f5f5, #222); padding: 3px 8px; border-radius: 4px; }}
.amount {{ font-size: 32px; font-weight: 700; text-align: center; margin: 24px 0; }}
.desc {{ font-size: 14px; color: light-dark(#666, #999); text-align: center; margin-bottom: 24px; }}
.details {{ margin-top: 20px; }}
.details summary {{ cursor: pointer; font-size: 12px; color: light-dark(#999, #666); }}
.details pre {{ background: light-dark(#f5f5f5, #1a1a1a); padding: 12px; border-radius: 8px; font-size: 11px; overflow-x: auto; margin-top: 8px; }}
</style>
</head>
<body>
<div class="card">
<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:8px">
<span class="badge">Payment Required</span>
{test_badge}
</div>
<div class="amount">{amount_display}</div>
{description_html}
<div id="root"></div>
<details class="details">
<summary>Challenge details</summary>
<pre>{challenge_json}</pre>
</details>
</div>
<script type="application/json" id="{data_id}">{embedded_json}</script>
<script>{payment_ui_js}</script>
</body>
</html>"#,
        test_badge = if test_badge.is_empty() {
            String::new()
        } else {
            test_badge
        },
        amount_display = escape_html(&amount_display),
        description_html = description_html,
        challenge_json = escape_html(&challenge_json),
        data_id = DATA_ELEMENT_ID,
        embedded_json = embedded_json,
        payment_ui_js = PAYMENT_UI_JS,
    )
}

/// HTML-escape a string to prevent XSS when interpolating into HTML content.
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::core::{
        types::{IntentName, MethodName},
        Base64UrlJson,
    };

    fn test_challenge(description: Option<&str>) -> PaymentChallenge {
        PaymentChallenge {
            id: "test-challenge-id".to_string(),
            realm: "test.example.com".to_string(),
            method: MethodName::new("solana"),
            intent: IntentName::new("charge"),
            request: Base64UrlJson::from_typed(
                &serde_json::json!({"amount": "1000000", "currency": "USDC", "recipient": "CXhrFZJLKqjzmP3sjYLcF4dTeXWKCy9e2SXXZ2Yo6MPY"}),
            ).unwrap(),
            expires: Some("2099-01-01T00:00:00Z".to_string()),
            description: description.map(|s| s.to_string()),
            digest: None,
            opaque: None,
        }
    }

    #[test]
    fn test_accepts_html() {
        assert!(accepts_html("text/html,application/xhtml+xml,*/*"));
        assert!(accepts_html("text/html"));
        assert!(!accepts_html("application/json"));
        assert!(!accepts_html("*/*")); // Don't match wildcard — be explicit
    }

    #[test]
    fn test_is_service_worker_request() {
        assert!(is_service_worker_request("__mpp_worker=1"));
        assert!(is_service_worker_request("foo=bar&__mpp_worker=1"));
        assert!(!is_service_worker_request("foo=bar"));
        assert!(!is_service_worker_request(""));
    }

    #[test]
    fn test_escape_html() {
        assert_eq!(
            escape_html("<script>alert('xss')</script>"),
            "&lt;script&gt;alert(&#x27;xss&#x27;)&lt;/script&gt;"
        );
    }

    #[test]
    fn test_service_worker_js_not_empty() {
        assert!(!service_worker_js().is_empty());
    }

    #[test]
    fn test_challenge_to_html_structure() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(&challenge, "https://api.devnet.solana.com", "devnet");

        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("id=\"root\""));
        assert!(html.contains("id=\"__MPP_DATA__\""));
        assert!(html.contains("test-challenge-id"));
        // Payment UI script should be inlined
        assert!(html.len() > 1000);
        // Test mode should be detected for devnet
        assert!(html.contains("\"testMode\":true"));
    }

    #[test]
    fn test_challenge_to_html_mainnet_not_test_mode() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(
            &challenge,
            "https://api.mainnet-beta.solana.com",
            "mainnet-beta",
        );
        assert!(html.contains("\"testMode\":false"));
    }

    #[test]
    fn test_challenge_to_html_xss_in_description() {
        let challenge = test_challenge(Some("<script>alert('xss')</script>"));
        let html = challenge_to_html(&challenge, "http://localhost:8899", "localnet");
        // The <script> in description must be escaped in the <p> tag
        assert!(html.contains("&lt;script&gt;alert("));
        // Raw script tag should NOT appear in description context
        assert!(!html.contains("<p style=\"color:#4a5568;text-align:center\"><script>"));
    }

    #[test]
    fn test_challenge_to_html_basic_structure() {
        let challenge = test_challenge(None);
        let html = challenge_to_html(&challenge, "http://localhost:8899", "devnet");
        // CSP is set as a response header by the server, not in the HTML meta tag.
        // Verify the HTML has the essential structural elements.
        assert!(html.contains("<div id=\"root\">"));
        assert!(html.contains("<script>"));
    }

    #[test]
    fn test_html_enabled_on_mpp() {
        let mpp = crate::server::Mpp::new(crate::server::Config {
            recipient: "CXhrFZJLKqjzmP3sjYLcF4dTeXWKCy9e2SXXZ2Yo6MPY".to_string(),
            secret_key: Some(
                "test-secret-key-long-enough-for-hmac-sha256-operations-1234567890".to_string(),
            ),
            network: "devnet".to_string(),
            html: true,
            ..Default::default()
        })
        .unwrap();

        assert!(mpp.html_enabled());
        assert_eq!(mpp.network(), "devnet");
        assert!(!mpp.rpc_url().is_empty());

        // Generate a challenge and render as HTML
        let challenge = mpp.charge("0.10").unwrap();
        let html = challenge_to_html(&challenge, mpp.rpc_url(), mpp.network());
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains(&challenge.id));
    }
}
